# Copyright 2026 The Helium Authors

source_set("helium_sync") {
  sources = [
    "helium_sync_service.cc",
    "helium_sync_service.h",
    "helium_sync_service_factory.cc",
    "helium_sync_service_factory.h",
  ]

  deps = [
    "//base",
    "//build:chromeos_buildflags",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/password_manager",
    "//chrome/browser/password_manager/factories",
    "//chrome/browser/profiles:profile",
    "//chrome/common",
    "//components/helium_sync",
    "//components/keyed_service/core",
    "//components/password_manager/core/browser/password_store:password_store_interface",
    "//services/network/public/cpp",
    "//url",
  ]
}
