# Copyright 2026 The Helium Authors

source_set("helium_sync") {
  sources = [
    "helium_cookie_sync_bridge.cc",
    "helium_cookie_sync_bridge.h",
    "helium_native_recovery_bridge.cc",
    "helium_native_recovery_bridge.h",
    "helium_sync_service.cc",
    "helium_sync_service.h",
    "helium_sync_service_factory.cc",
    "helium_sync_service_factory.h",
    "helium_tab_restore_bridge.cc",
    "helium_tab_restore_bridge.h",
    "helium_tab_snapshot_bridge.cc",
    "helium_tab_snapshot_bridge.h",
  ]

  deps = [
    "//base",
    "//build:chromeos_buildflags",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/password_manager",
    "//chrome/browser/password_manager/factories",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/tab_list",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/browser_window:create_browser_window",
    "//chrome/common",
    "//components/helium_sync",
    "//components/keyed_service/core",
    "//components/password_manager/core/browser/password_store:password_store_interface",
    "//components/password_manager/core/browser/sync",
    "//components/sync/protocol",
    "//components/sessions",
    "//components/sessions:session_id",
    "//components/tab_groups",
    "//components/tabs:public",
    "//content/public/browser",
    "//crypto",
    "//net",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//ui/base",
    "//url",
  ]
}
